theme: jekyll-theme-architect
title: ATENEA
description: Clases y Cursos Personalizados
locale: es_CO
logo: ![logo](./logo2p.svg)
owner: John Erick Cabrera Ramirez
name: John Erick Cabrera 
#avatar: bio-photo.jpg
bio: "Físico UNAL y candidato a magíster en física uniandes. Interesado en nuevas formas de enseñanza y en estudios interdisciplinarios."
email: clasesyaprendizaje@gmail.com
facebook: ClasesAtenea
  # Do not include the @ symbol in your Twitter username
twitter: cla_aprendizaje
 #linkedin: #username
github: jerck1
# Site navigation links
- title: Home
  url: /
- title: Home
  url: ./Materias/Matemáticas.md
